#!/usr/bin/env node

/**
 * regenerate-portals.mjs — Resync portals.yml to current keywords (and optionally
 * seed tracked_companies from the template).
 *
 * What gets regenerated (overwritten in portals.yml):
 *   title_filter.positive    — from enabled keywords in data/keywords.json
 *   search_queries           — 1 query per keyword × each WebSearch template
 *   linkedin.searches        — 1 search per keyword
 *
 * What is preserved:
 *   title_filter.negative
 *   title_filter.seniority_boost
 *   tracked_companies        — user-curated (unless --seed-tracked)
 *   All top-level comments
 *
 * Optional: --seed-tracked
 *   Copies the tracked_companies list from templates/portals.example.yml
 *   into portals.yml. Only effective when your current tracked_companies
 *   is empty, unless you also pass --force.
 *
 * Usage:
 *   node regenerate-portals.mjs                           # resync from keywords
 *   node regenerate-portals.mjs --seed-tracked            # also seed companies if empty
 *   node regenerate-portals.mjs --seed-tracked --force    # overwrite existing companies
 *   node regenerate-portals.mjs --dry-run                 # preview without writing
 */

import { readFileSync, writeFileSync, existsSync, copyFileSync } from 'fs';
import yaml from 'js-yaml';

const KEYWORDS_PATH = 'data/keywords.json';
const PORTALS_PATH = 'portals.yml';
const TEMPLATE_PATH = 'templates/portals.example.yml';
const BACKUP_PATH = 'portals.yml.backup';

// Each template emits one WebSearch query per enabled keyword.
// Keep this list small — more templates = more API cost per scan.
const WEBSEARCH_TEMPLATES = [
  { name: 'LinkedIn', site: 'linkedin.com/jobs', remote: true },
  { name: 'Greenhouse', site: 'boards.greenhouse.io', remote: true },
  { name: 'Ashby', site: 'jobs.ashbyhq.com', remote: false },
];

// ── Keyword loading ───────────────────────────────────────────

function loadEnabledKeywords() {
  if (!existsSync(KEYWORDS_PATH)) {
    throw new Error(`${KEYWORDS_PATH} not found. Run \`node generate-keywords.mjs\` first.`);
  }
  const data = JSON.parse(readFileSync(KEYWORDS_PATH, 'utf8'));
  const enabled = [
    ...(data.keywords || []).filter(k => k.enabled),
    ...(data.user_added || []).filter(k => k.enabled),
  ];
  // Dedupe case-insensitively, preserve first casing seen
  const unique = new Map();
  for (const k of enabled) {
    const key = k.term.toLowerCase();
    if (!unique.has(key)) unique.set(key, k.term);
  }
  return Array.from(unique.values());
}

// ── YAML block generation ─────────────────────────────────────

function yamlEscape(s) {
  return s.replace(/"/g, '\\"');
}

function generatePositiveBlock(keywords) {
  return keywords.map(kw => `    - "${yamlEscape(kw)}"`).join('\n');
}

function generateSearchQueriesBlock(keywords) {
  const banner =
    '  # AUTO-GENERATED by regenerate-portals.mjs from data/keywords.json.\n' +
    '  # Edits will be overwritten on next regenerate. Change keywords in the Keywords tab instead.';

  const entries = [];
  for (const kw of keywords) {
    for (const tpl of WEBSEARCH_TEMPLATES) {
      const remoteSuffix = tpl.remote ? ' remote' : '';
      const nameSuffix = tpl.remote ? ' (Remote)' : '';
      const safe = yamlEscape(kw);
      entries.push(
        `  - name: "${tpl.name} — ${safe}${nameSuffix}"\n` +
        `    query: 'site:${tpl.site} "${safe}"${remoteSuffix}'\n` +
        `    enabled: true`
      );
    }
  }
  return `${banner}\n\n${entries.join('\n\n')}`;
}

function generateLinkedinSearchesBlock(keywords) {
  const banner =
    '    # AUTO-GENERATED by regenerate-portals.mjs from data/keywords.json.';
  const lines = keywords.map(kw => {
    const safe = yamlEscape(kw);
    return `    - { name: "LinkedIn — ${safe} (Remote)", q: "${safe}", remote: true }`;
  });
  return `${banner}\n${lines.join('\n')}`;
}

// ── Section replacement (regex-based, preserves comments outside each section) ──

function replaceSection(content, pattern, replacement, sectionName) {
  if (!pattern.test(content)) {
    throw new Error(`Could not find '${sectionName}' in portals.yml — file structure is non-standard. Back up your file and run onboarding again, or edit by hand.`);
  }
  return content.replace(pattern, replacement);
}

function replaceTitleFilterPositive(content, block) {
  return replaceSection(
    content,
    /title_filter:\n  positive:\n[\s\S]*?(?=\n  [a-z_]+:)/,
    `title_filter:\n  positive:\n${block}\n`,
    'title_filter.positive'
  );
}

function replaceSearchQueries(content, block) {
  return replaceSection(
    content,
    /search_queries:\n[\s\S]*?(?=\n[a-z_]+:)/,
    `search_queries:\n\n${block}\n`,
    'search_queries'
  );
}

function replaceLinkedinSearches(content, block) {
  // linkedin.searches is often the last top-level section — fall back to end of file
  return replaceSection(
    content,
    /linkedin:\n(\s{2}[^\n]*\n)*?\s{2}searches:\n[\s\S]*?(?=\n[a-z_]+:|$)/,
    (match) => {
      // Preserve any pre-searches content under linkedin: (like comments or auth config)
      const preSearches = match.replace(/\s{2}searches:\n[\s\S]*$/, '  searches:\n');
      return `${preSearches}${block}\n`;
    },
    'linkedin.searches'
  );
}

// ── Tracked companies seeding ─────────────────────────────────

function parseTrackedCompaniesFromYaml(yamlText) {
  try {
    const parsed = yaml.load(yamlText) || {};
    return Array.isArray(parsed.tracked_companies) ? parsed.tracked_companies : [];
  } catch {
    return [];
  }
}

function getCurrentTrackedCompanies(content) {
  return parseTrackedCompaniesFromYaml(content);
}

function seedTrackedCompanies(content, companies) {
  // Replace the tracked_companies section entirely with a fresh list
  const banner =
    '  # Seeded from templates/portals.example.yml by regenerate-portals.mjs --seed-tracked.\n' +
    '  # Set enabled: false on any company you don\'t want to scan.';

  const serialized = yaml
    .dump({ tracked_companies: companies }, { lineWidth: 140, noRefs: true, quotingType: '"' })
    .replace(/^tracked_companies:\n/, ''); // strip the top-level key, we re-add it

  // Pattern: tracked_companies: followed by either [] or indented list, until next top-level key
  const pattern = /tracked_companies:\s*\n[\s\S]*?(?=\n[a-z_]+:)|tracked_companies:\s*\[\s*\]\s*\n/;
  if (!pattern.test(content)) {
    throw new Error('Could not locate tracked_companies section.');
  }
  return content.replace(pattern, `tracked_companies:\n${banner}\n${serialized}\n`);
}

// ── Main ──────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const seedTracked = args.includes('--seed-tracked');
  const force = args.includes('--force');

  if (!existsSync(PORTALS_PATH)) {
    console.error(`ERROR: ${PORTALS_PATH} not found. Run onboarding first.`);
    process.exit(1);
  }

  const keywords = loadEnabledKeywords();
  if (keywords.length === 0) {
    console.error('ERROR: No enabled keywords in data/keywords.json');
    process.exit(1);
  }

  let content = readFileSync(PORTALS_PATH, 'utf8');
  const original = content;

  // 1. Regenerate derived sections from keywords
  content = replaceTitleFilterPositive(content, generatePositiveBlock(keywords));
  content = replaceSearchQueries(content, generateSearchQueriesBlock(keywords));
  content = replaceLinkedinSearches(content, generateLinkedinSearchesBlock(keywords));

  const queryCount = keywords.length * WEBSEARCH_TEMPLATES.length;
  const summary = {
    regenerated: {
      titleFilterPositive: keywords.length,
      searchQueries: queryCount,
      linkedinSearches: keywords.length,
    },
    preserved: {
      trackedCompaniesBefore: getCurrentTrackedCompanies(original).length,
      negativesBefore: (original.match(/negative:\s*\n([\s\S]*?)(?=\n  [a-z])/)?.[1] || '').split('\n').filter(l => l.trim().startsWith('-')).length,
    },
  };

  // 2. Optionally seed tracked_companies from template
  if (seedTracked) {
    if (!existsSync(TEMPLATE_PATH)) {
      console.error(`ERROR: ${TEMPLATE_PATH} not found. Cannot seed tracked_companies.`);
      process.exit(1);
    }
    const templateCompanies = parseTrackedCompaniesFromYaml(readFileSync(TEMPLATE_PATH, 'utf8'));
    const currentCompanies = getCurrentTrackedCompanies(content);

    if (currentCompanies.length > 0 && !force) {
      console.error(`ERROR: tracked_companies already has ${currentCompanies.length} entries. Pass --force to overwrite.`);
      process.exit(1);
    }

    content = seedTrackedCompanies(content, templateCompanies);
    summary.seededTrackedCompanies = templateCompanies.length;
  }

  // ── Report ──
  console.log('Regenerated from keywords.json:');
  console.log(`  title_filter.positive: ${summary.regenerated.titleFilterPositive} keywords`);
  console.log(`  search_queries:        ${summary.regenerated.searchQueries} queries (${keywords.length} kw × ${WEBSEARCH_TEMPLATES.length} templates)`);
  console.log(`  linkedin.searches:     ${summary.regenerated.linkedinSearches} searches`);
  if (summary.seededTrackedCompanies !== undefined) {
    console.log(`\nSeeded from template:`);
    console.log(`  tracked_companies:     ${summary.seededTrackedCompanies} companies`);
  } else {
    console.log(`\nPreserved:`);
    console.log(`  tracked_companies:     ${summary.preserved.trackedCompaniesBefore} companies (unchanged)`);
    if (summary.preserved.trackedCompaniesBefore === 0) {
      const templateExists = existsSync(TEMPLATE_PATH);
      if (templateExists) {
        const n = parseTrackedCompaniesFromYaml(readFileSync(TEMPLATE_PATH, 'utf8')).length;
        console.log(`  → Note: ${TEMPLATE_PATH} has ${n} pre-configured companies available.`);
        console.log(`  → Run again with --seed-tracked to import them.`);
      }
    }
  }

  if (dryRun) {
    console.log('\n(dry run — no changes written)');
    return;
  }

  copyFileSync(PORTALS_PATH, BACKUP_PATH);
  writeFileSync(PORTALS_PATH, content, 'utf8');
  console.log(`\nWrote ${PORTALS_PATH} (backup saved at ${BACKUP_PATH})`);
}

main();
